Vikranth Reddy Thirumala

700758559

1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sai Ram", "Uppalapati", 100000, "Manager")
employee2 = Employee("Venkat", "Uppalapati", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhavi", "Uppalapati", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Nandhu", "Nandini", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)



Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [6]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 6.65642661  7.69225756 18.73437165 19.36234067 16.83242973 19.33578929
 11.02394867 17.4898039  18.89160035  2.33628585  3.6735787  17.96372376
 18.95709591  2.58718871  3.38511527 19.10582994 13.3366162   9.93303247
  5.64069407 15.06626796]


In [3]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[10.81728371  9.8083229  19.25639332 13.70327927  8.50656585]
 [17.0482618  16.94650923 14.56784185  1.79132324 19.57735231]
 [ 7.81462763 10.15078766 16.59223712  8.66864088  7.61637472]
 [14.99408277 16.45624546 17.92200752 13.87972128  6.90624646]]


In [7]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[10.81728371  9.8083229   0.         13.70327927  8.50656585]
 [17.0482618  16.94650923 14.56784185  1.79132324  0.        ]
 [ 7.81462763 10.15078766  0.          8.66864088  7.61637472]
 [14.99408277 16.45624546  0.         13.87972128  6.90624646]]
